### ISSUE TITLE
setup.py and pypi distribution for Icarus

### ISSUE THREAD

**Issue by muddassir235** [bretonr/Icarus#1]
I want to add a  simple setup.py file that adds Icarus to the `PYTHONPATH`.
It will also include code to add Icarus to pypi so that it can be simply installed
using the " `pip install icarus` " command.
Please let me know if this is wanted and any suggestions?

**Comment by bretonr** [comment]
Hi,

I'm certainly happy to do so. I can look into it but if you have time and want to make a pull request I'll be happy to merge it in the main branch.

Cheers

Rene

---

**Comment by muddassir235** [comment]
I'll get it ready in this working week. And make a pull request!

**Comment by bretonr** [comment]
Great!

---

**Comment by bretonr** [comment]
Accepted the commit. Will look into pypi now.
